# 重新加载数据

In [1]:
import sys
from pathlib import Path
import pandas as pd
import numpy as np
import math

PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

sys.path.append(str(PROJECT_ROOT))

from src.data_processing import load_marketing_data

df = load_marketing_data(PROJECT_ROOT / "data" / "raw" / "marketing_AB.csv")

df.head()

   user_id test_group  converted  total_ads most_ads_day  most_ads_hour
0  1069124         ad      False        130       Monday             20
1  1119715         ad      False         93      Tuesday             22
2  1144181         ad      False         21      Tuesday             18
3  1435133         ad      False        355      Tuesday             10
4  1015700         ad      False        276       Friday             14

# 汇总两组转化情况

In [2]:
ab_summary = df.groupby("test_group").agg(
    users=("user_id", "count"),
    conversions=("converted", "sum"),
    conversion_rate=("converted", "mean")
).reset_index()

ab_summary["conversion_rate_pct"] = ab_summary["conversion_rate"] * 100

ab_summary

  test_group   users  conversions  conversion_rate  conversion_rate_pct
0         ad  564577        14423         0.025547             2.554656
1        psa   23524          420         0.017854             1.785411

## 检验两组用户转化率是否存在统计显著差异

In [3]:
ad = ab_summary[ab_summary["test_group"] == "ad"].iloc[0]
psa = ab_summary[ab_summary["test_group"] == "psa"].iloc[0]

x_ad = ad["conversions"]
n_ad = ad["users"]

x_psa = psa["conversions"]
n_psa = psa["users"]

p_ad = x_ad / n_ad
p_psa = x_psa / n_psa

p_pool = (x_ad + x_psa) / (n_ad + n_psa)

standard_error = math.sqrt(
    p_pool * (1 - p_pool) * (1 / n_ad + 1 / n_psa)
)

z_score = (p_ad - p_psa) / standard_error

p_value = 2 * (1 - 0.5 * (1 + math.erf(abs(z_score) / math.sqrt(2))))

result = pd.DataFrame({
    "metric": [
        "ad_conversion_rate",
        "psa_conversion_rate",
        "absolute_lift",
        "relative_lift",
        "z_score",
        "p_value"
    ],
    "value": [
        p_ad,
        p_psa,
        p_ad - p_psa,
        (p_ad - p_psa) / p_psa,
        z_score,
        p_value
    ]
})

result

                metric         value
0   ad_conversion_rate  2.554656e-02
1  psa_conversion_rate  1.785411e-02
2        absolute_lift  7.692453e-03
3        relative_lift  4.308506e-01
4              z_score  7.370078e+00
5              p_value  1.705303e-13

## 95% 置信区间

In [4]:
se_unpooled = math.sqrt(
    p_ad * (1 - p_ad) / n_ad + 
    p_psa * (1 - p_psa) / n_psa
)

ci_low = (p_ad - p_psa) - 1.96 * se_unpooled
ci_high = (p_ad - p_psa) + 1.96 * se_unpooled

ci_result = pd.DataFrame({
    "metric": [
        "absolute_lift",
        "ci_low_95",
        "ci_high_95"
    ],
    "value": [
        p_ad - p_psa,
        ci_low,
        ci_high
    ]
})

ci_result

          metric     value
0  absolute_lift  0.007692
1      ci_low_95  0.005951
2     ci_high_95  0.009434

## A/B 测试结果

广告组的转化率高于 PSA 对照组。
广告组转化率约为 2.55%，PSA 对照组为 1.79%。
本研究检验两组转化率差异是否具备统计显著性，结果表明两组存在统计学意义上的差异，说明广告干预与更高的转化概率存在关联。
绝对提升幅度约 0.77 个百分点，相对提升幅度约 43%。
但由于广告曝光频次与转化行为高度相关，该结果需要结合后续的曝光与时间维度分析共同解读。

### 在曝光次数、星期、小时都被控制住以后，ad 组是否仍然比 psa 组更容易转化？

In [6]:
import statsmodels.formula.api as smf
import numpy as np

model_df = df.copy()

model_df["converted_int"] = model_df["converted"].astype(int)
model_df["is_ad"] = (model_df["test_group"] == "ad").astype(int)

model_df["log_total_ads"] = np.log1p(model_df["total_ads"])

logit_model = smf.logit(
    formula="converted_int ~ is_ad + log_total_ads + C(most_ads_day) + C(most_ads_hour)",
    data=model_df
).fit()

print(logit_model.summary())

Optimization terminated successfully.
         Current function value: 0.094961
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:          converted_int   No. Observations:               588101
Model:                          Logit   Df Residuals:                   588069
Method:                           MLE   Df Model:                           31
Date:                Sat, 19 Sep 2026   Pseudo R-squ.:                  0.1938
Time:                        17:08:49   Log-Likelihood:                -55846.
converged:                       True   LL-Null:                       -69267.
Covariance Type:            nonrobust   LLR p-value:                     0.000
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                       -8.5601      0.122    -70.093      0.000      -8.799      -8.321
C(most_ads_day)[T.Monday]        0.4968      0.031     16.078      0.000       0.436       0.557
C(most_ads_day)[T.Saturday]      0.0138      0.034      0.402      0.688      -0.054       0.081
C(most_ads_day)[T.Sunday]        0.2061      0.033      6.283      0.000       0.142       0.270
C(most_ads_day)[T.Thursday]      0.1198      0.034      3.505      0.000       0.053       0.187
C(most_ads_day)[T.Tuesday]       0.4617      0.032     14.312      0.000       0.398       0.525
C(most_ads_day)[T.Wednesday]     0.2459      0.033      7.391      0.000       0.181       0.311
C(most_ads_hour)[T.1]           -0.4893      0.167     -2.936      0.003      -0.816      -0.163
C(most_ads_hour)[T.2]           -1.0691      0.194     -5.519      0.000      -1.449      -0.689
C(most_ads_hour)[T.3]           -0.6067      0.220     -2.759      0.006      -1.038      -0.176
C(most_ads_hour)[T.4]           -0.6890      0.331     -2.084      0.037      -1.337      -0.041
C(most_ads_hour)[T.5]           -0.6312      0.284     -2.224      0.026      -1.188      -0.075
C(most_ads_hour)[T.6]           -0.5126      0.186     -2.751      0.006      -0.878      -0.147
C(most_ads_hour)[T.7]           -0.3707      0.142     -2.607      0.009      -0.649      -0.092
C(most_ads_hour)[T.8]           -0.0077      0.118     -0.066      0.948      -0.239       0.224
C(most_ads_hour)[T.9]           -0.0165      0.112     -0.147      0.883      -0.236       0.203
C(most_ads_hour)[T.10]           0.0303      0.110      0.277      0.782      -0.185       0.245
C(most_ads_hour)[T.11]           0.0758      0.109      0.698      0.485      -0.137       0.289
C(most_ads_hour)[T.12]           0.1032      0.108      0.954      0.340      -0.109       0.315
C(most_ads_hour)[T.13]           0.1648      0.108      1.527      0.127      -0.047       0.376
C(most_ads_hour)[T.14]           0.3691      0.108      3.430      0.001       0.158       0.580
C(most_ads_hour)[T.15]           0.3846      0.108      3.576      0.000       0.174       0.595
C(most_ads_hour)[T.16]           0.5779      0.108      5.348      0.000       0.366       0.790
C(most_ads_hour)[T.17]           0.3809      0.109      3.500      0.000       0.168       0.594
C(most_ads_hour)[T.18]           0.2922      0.109      2.670      0.008       0.078       0.507
C(most_ads_hour)[T.19]           0.2675      0.110      2.433      0.015       0.052       0.483
C(most_ads_hour)[T.20]           0.3521      0.110      3.212      0.001       0.137       0.567
C(most_ads_hour)[T.21]           0.3601      0.110      3.288      0.001       0.145       0.575
C(most_ads_hour)[T.22]           0.3803      0.111      3.428      0.001       0.163       0.598
C(most_ads_hour)[T.23]           0.3837      0.114      3.355      0.001       0.160       0.608
is_ad                            0.3926      0.052      7.569      0.000       0.291       0.494
log_total_ads                    1.2273      0.008    145.780      0.000       1.211       1.244
================================================================================================

# 提取广告效果

In [7]:
coef = logit_model.params["is_ad"]
p_value = logit_model.pvalues["is_ad"]

odds_ratio = np.exp(coef)

logit_result = pd.DataFrame({
    "metric": ["ad_coefficient", "odds_ratio", "p_value"],
    "value": [coef, odds_ratio, p_value]
})

logit_result

           metric         value
0  ad_coefficient  3.926148e-01
1      odds_ratio  1.480848e+00
2         p_value  3.748344e-14

### 假设所有用户的曝光次数、星期、小时分布都一样，只改变他们是否属于 ad 组，那么平均预测转化率会差多少？

In [8]:
ad_case = model_df.copy()
psa_case = model_df.copy()

ad_case["is_ad"] = 1
psa_case["is_ad"] = 0

adjusted_ad_rate = logit_model.predict(ad_case).mean()
adjusted_psa_rate = logit_model.predict(psa_case).mean()

adjusted_absolute_lift = adjusted_ad_rate - adjusted_psa_rate
adjusted_relative_lift = adjusted_absolute_lift / adjusted_psa_rate

adjusted_result = pd.DataFrame({
    "metric": [
        "adjusted_ad_conversion_rate",
        "adjusted_psa_conversion_rate",
        "adjusted_absolute_lift",
        "adjusted_relative_lift"
    ],
    "value": [
        adjusted_ad_rate,
        adjusted_psa_rate,
        adjusted_absolute_lift,
        adjusted_relative_lift
    ]
})

adjusted_result

                         metric     value
0   adjusted_ad_conversion_rate  0.025542
1  adjusted_psa_conversion_rate  0.017927
2        adjusted_absolute_lift  0.007615
3        adjusted_relative_lift  0.424778

## 调整后的实验处理效应

通过逻辑回归对广告曝光频次、用户广告活跃高峰日、广告活跃高峰小时进行控制之后，广告组的预测转化率依旧高于 PSA 对照组。

调整后广告组转化率约为 2.55%，PSA 对照组约为 1.79%。
调整后的绝对提升约 0.76 个百分点，对应的调整后相对提升约 42.48%。

该结果与原始 A/B 测试得到的提升幅度十分接近，说明在纳入曝光与时间因素进行校正后，广告带来的正向实验效应依旧稳健。